### ISSUE TITLE
Make the manual available online

### ISSUE THREAD

**Issue by vadz** [vslavik/xmlwrapp#23]
It would be nice to have the manual available online, e.g. at http://vslavik.github.io/xmlwrapp/

Ideal would be to update it automatically, of course, but even if this can't be done, it would still be useful to have it, it doesn't change that often so keeping it up to date manually shouldn't be a big problem.

**Comment by vslavik** [comment]
The page uses GitHub Pages and I think it isn’t worth bothering with automation, it would suffice to push updates manually (see e.g. http://rickfoosusa.blogspot.com/2011/10/howto-use-doxygen-with-github.html) to the `gh-pages` branch.
