### ISSUE TITLE
./configure --disable-tests not working

### ISSUE THREAD

**Issue by juusotam** [vslavik/xmlwrapp#25]
./configure --disable-tests gives warning

configure: WARNING: unrecognized options: --disable-tests

and make fails:

Making all in tests
  CXX      test_main.o
In file included from test_main.cxx:34:
./test.h:39:10: fatal error: 'boost/test/unit_test.hpp' file not found
#include <boost/test/unit_test.hpp>
         ^
1 error generated.
make[1]: *** [test_main.o] Error 1
make: *** [all-recursive] Error 1

**Comment by vadz** [comment]
This definitely works for me, please check if your `configure` is not out of date somehow by running `./bootstrap`.

I also *strongly* recommend running configure from a different directly.
