### ISSUE TITLE
Not compatible with C++17

### ISSUE THREAD

**Issue by ErikLevin** [vslavik/xmlwrapp#62]
_cbfo.h uses [std::binary_function](https://en.cppreference.com/w/cpp/utility/functional/binary_function), which is removed in C++17.

**Comment by vadz** [comment]
Strange, somehow both gcc 9 and clang 10 compile this just fine with `-std=c++17` even though it looks like they indeed shouldn't. But, in any case, we should get rid of `binary_function` when using C++11 (or maybe even unconditionally? It's not as if it were really useful anyhow...).

I'll try to do it, although any PRs would be welcome too.

**Comment by vadz** [comment]
BTW, the explanation for why gcc 9 has no problem with this code is [here](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91260) (and I'm glad that gcc/libstdc++ developers have chosen not to break the existing code). I couldn't find anything like this for clang/libc++ though, so I guess it's still better to prepare for its removal, or at least deprecation there. I'm curious which compiler did you use to find this problem.

**Comment by ErikLevin** [comment]
I used Visual Studio 2019 with C++ standard option set to std:c++17.

**Comment by vadz** [comment]
There is something I'm missing here because this is my primary compiler too, and I use it with `/std:c++17` and didn't have any problems. Anyhow, it shouldn't be an issue any longer.
