### ISSUE TITLE
Information on exception

### ISSUE THREAD

**Issue by jm130794** [vslavik/xmlwrapp#65]
Hello,

Is it possible to have more information about an exception?

When I catch an exception, I get the error message but not the number of the line at fault.

Thank you for your help.

Jean-Marc

**Comment by vslavik** [comment]
That's not part of C++ exceptions.

**Comment by jm130794** [comment]
OK.

So how do we do it?

I use Schema.validate to validate the syntax of an XML file. How can I get more precision on the location of the error?

Jean-Marc

**Comment by vslavik** [comment]
It wasn't really clear that you're talking about *parsing errors*, and not exceptions in general. Please do read [this](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) — it's a great guide on describing problems in a way that others can understand.

On the subject of information about parsing errors, see #39.

**Comment by jm130794** [comment]
Excuse me if it wasn't really clear.

I just want to know the position of the problem in the XML file when validating with an XSD file. 

For example, if I use libxml2 directly with my xml and xsd files, here is an example of the errors I encountered :

guacamole.xml:12: element user: Schemas validity error : Element 'user', attribute 'id': The attribute 'id' is not allowed.
guacamole.xml:12: element user: Schemas validity error : Element 'user': The attribute 'uid' is required but missing.

The message is clear.

With xmlwrapp, here is the output :
Element 'user', attribute 'id': The attribute 'id' is not allowed.

This is unusable for a large XML file.

I'm new with xmlwrapp and I don't kown how to get equivalent information. Maybe it's impossible...

Jean-Marc
